# Copyright 2014 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

os: linux
dist: bionic
language: go

jobs:
  include:
  - go: 1.14.x
    cache:
      directories:
        - $GOPATH/pkg/mod
        # Cache tools sources. Manually verified that both misspell and ineffassign
        # only depend on the stdlib.
        - $GOPATH/src/github\.com/client9
        - $GOPATH/src/github\.com/gordonklaus
        # For shadow.
        - $GOPATH/src/golang\.org
    before_script:
    - echo $TRAVIS_GO_VERSION
    - >
      go get -u -v
      github.com/client9/misspell/cmd/misspell
      github.com/gordonklaus/ineffassign
      golang.org/x/lint/golint
      golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
    script:
    - echo 'Check Code is well formatted'; ! gofmt -s -d . | read
    - go list ./... | grep -v /vendor/ | xargs -L1 golint -set_exit_status
    - go vet ./...
    - go vet -vettool=$GOPATH/bin/shadow
    - ineffassign .
    - bash -c 'set -e; echo "" > coverage.txt; for d in $(go list ./...); do go test -covermode=count -coverprofile=p.out $d; if [ -f p.out ]; then cat p.out >> coverage.txt; rm p.out; fi; done'
    - go test -race ./...
    - if find . -path ./.git -prune -o -type f -executable -print | grep -e . ; then echo 'Do not commit executables'; false; fi
    after_success:
    - bash <(curl -s https://codecov.io/bash)

  - go: 1.12.17
    before_script:
    - echo $TRAVIS_GO_VERSION
    script:
    - go test ./...

  - go: 1.8.7
    before_script:
    - echo $TRAVIS_GO_VERSION
    script:
    - go test ./...
