# Copyright 2014 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

sudo: false
language: go

go:
- 1.8.7
- 1.x

before_install:
- if [[ $TRAVIS_GO_VERSION != 1.8.7 ]]; then GO111MODULE=off go get github.com/maruel/pre-commit-go/cmd/pcg; fi

script:
- if [[ $TRAVIS_GO_VERSION != 1.8.7 ]]; then GO111MODULE=off pcg; fi
# Only run a short suite on go1.8.7. For example goimports doesn't build on
# go1.8 anymore.
- if [[ $TRAVIS_GO_VERSION == 1.8.7 ]]; then go test ./...; fi
